/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package comparador.rugido.animal;

import comparador.rugido.animal.animais.Gato;
import comparador.rugido.animal.animais.Leao;

public class App {

    public static void main(String[] args) {
     
        ComparadorRugidoAnimal comparadorRugidoAnimal = new ComparadorRugidoAnimal();

        String tipoAnimal = comparadorRugidoAnimal.Comparar(new Gato(), new Leao());

        System.out.println("Animal com maior rugido: " + tipoAnimal);

    }
}
